### ISSUE TITLE
Boolean Properties Generation in String

### ISSUE THREAD

**Issue by ViktorOdin** [alien4cloud/alien4cloud-cloudify2-provider#1]
The Tosca node definition have a boolean properties but the recip generated write it between quote like a string

definition file:

``` yaml
...
node_types:
  fasconnect.nodes.iis:
    derived_from: tosca.nodes.SoftwareComponent
...
    properties:
      dotNetInstall:
        type: boolean
        default: false
...
```

test in groovy file:

``` groovy
def dotNetInstall = config.get(serviceName).dotNetInstall

if(dotNetInstall){
    ...
}
```

properties generated:

``` groovy
...
iis.dotNetInstall="false"
...
```
